### ISSUE TITLE
Properly handle non-english keyboard inputs

### ISSUE THREAD

**Issue by Datewro** [Quaver/Quaver#3946]
### Describe the bug

Quaver skip some keys
Quaver skip my keys while i'm playing making me lose, like i touch them but it doesn't count like i press the note.

To Reproduce (at least my problem)

Go to 'any song'
Click on 'play'
Get ready to play

4. See error 'Keys touch but doesn't count'
Is not my keyboard!! ;;
I tried to do with other keyboard (i tought it was my keyboard) but the problem still hapen, but then i play other game with the piano style, using the same keybindings, and it work well, so is Quaver giving me problems

Desktop:

Windows (?)
Opera GX
Version w10

Thank you! and if you can help me! or fix the bug, I do not know if anyone has the same problem. Sorry if something isn't clear, english is not my first language.

**Comment by Illuminati-CRAZ** [comment]
Have you been playing with a non-english input method? I think in the past, the game didn't register certain other language's inputs properly, and I don't think we've gotten around to fixing that yet.

**Comment by Datewro** [comment]
> Have you been playing with a non-english input method? I think in the past, the game didn't register certain other language's inputs properly, and I don't think we've gotten around to fixing that yet.

Apologies for the delayed response and for not using the issue system correctly. Yes, my input method was set to Portuguese (Brazil), I switched to English (United States), and the problem was resolved. Thank you so much for your assistance; you deserve all the best. You saved my life. Great job! Have an excellent day.

**Comment by YaLTeR** [comment]
fwiw on linux it already works as it should; even with my colemak and russian layouts, the in-game binds use qwerty, which means they go through the physical buttons. I'm not sure what's the deal on Windows, maybe just updating SDL might help?

**Comment by Glebsin** [comment]
This issue is still present. I have US and RU keyboard layouts, the main 4K keys are A, D, L, and '. When the RU layout is enabled, the ' key does not work, and the restart key ` also does not work.
