### ISSUE TITLE
pause bug

### ISSUE THREAD

**Issue by aaronjdb15** [Quaver/Quaver#4103]
### Describe the bug

when you hit esc and ` at the same time, if you don't move the mouse over it, the pause screen goes off to the left

### To Reproduce

idk

### Log Files

idk

### Screenshots

![2024-05-01 09 04 39](https://github.com/Quaver/Quaver/assets/127987870/ffda8bcb-44d8-46f3-88cf-cdf535909a6f)

**Comment by derwFi** [comment]
that's when you're going to the pause screen too early (by clicking esc rapidly)

**Comment by TDMG-NL** [comment]
I can't seem to reproduce this issue, this might have been fixed already in a previous version

**Comment by AiAe** [comment]
> I can't seem to reproduce this issue, this might have been fixed already in a previous version

You can probably still reproduce it when u hit pause and u instantly click on the arrow down key. At least thats how I used to get that bug. I don't think that we fixed it yet?

There is also similar bug which does the same in the main menu, where the animations stop if u press arrow up/down before they finish

**Comment by TDMG-NL** [comment]
> You can probably still reproduce it when u hit pause and u instantly click on the arrow down key. At least thats how I used to get that bug. I don't think that we fixed it yet?
> 

i had tap to pause turned to off which is why i couldn't reproduce. I'll be looking into it 👍
