### ISSUE TITLE
Ascending/Descending order does not work when something is searched

### ISSUE THREAD

**Issue by ARGEBE** [Quaver/Quaver#4356]
### Describe the bug

Not too much to clarify, when in the download maps page (on canary), trying to use the ascending/descending options simply don't do anything

### To Reproduce

1. Go to download maps
2. Search something
3. Try to change Ascending to Descending

### Expected behavior

They should have inverse ordering

### Log Files

Nothing is written to logs

### Screenshots

![11212024 18-21-56-855](https://github.com/user-attachments/assets/24cb1ab0-c9e8-41d6-be34-8565bbbbbaef)
![11212024 18-22-6-389](https://github.com/user-attachments/assets/bc57d7b3-8c50-4bc8-8e7c-ee34a8559e0f)

**Comment by KGBofficial** [comment]
Legends foretell of this issue being taken care of one day, eventually...

**Comment by 7ef38c** [comment]
Fixed in https://github.com/Quaver/api-v2/pull/152

**Comment by AiAe** [comment]
Technically not fully fixed, the asc/desc needs to be flipped on how they function
